# Usa una base con Python installato
FROM python:3.13.3-slim-bullseye

# Installa le dipendenze necessarie per pygame e X11
RUN apt-get update && apt-get install -y \
    python3-dev \
    libsdl-image1.2-dev \
    libsdl-mixer1.2-dev \
    libsdl-ttf2.0-dev \
    libsdl1.2-dev \
    libsmpeg-dev \
    libsdl1.2debian \
    libportmidi-dev \
    ffmpeg \
    libswscale-dev \
    libavformat-dev \
    libavcodec-dev \
    libx11-6 \
    libx11-dev \
    x11-utils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file dell'app nel container
COPY . /app

# Installa pygame e altre dipendenze Python
RUN pip install --no-cache-dir pygame

# Comando di default per avviare lo script principale
CMD ["python", "main.py"]
