FROM gcc:latest

RUN apt-get update && apt-get install -y \
    make \
    libjansson-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY src ./src
COPY includes ./includes
COPY Makefile .

RUN make

EXPOSE 8080

CMD ["./tris_server"]